let suggestions = [
    "Channel",
    "Kids",
    "Electronics",
    "Men's wear",
    "Women's wear",
    "YouTube Channel",
    "Trousers",
    "Jeans",
    "Skirts",
    "Furniture",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Laptops",
    "Earphones",
    "Shoes",
    "Jekkings",
    "DYI products",
    "sales",
    "Javascript Books",
    "LEDS,LCDs,Bravio",
    "Lens , spectacles",
    "Watches",
    "festival offers",
    "Amazon Payments",
    "Sports Wear",
];